## Self-Attention Implementation

In [ ]:
# libraries
import numpy as np

# class
class SelfAttention:
    def __init__(self, d_model, d_k, d_v):
        self.d_k = d_k
        self.W_Q = np.random.randn(d_model, d_k) * 0.01
        self.W_K = np.random.randn(d_model, d_k) * 0.01
        self.W_V = np.random.randn(d_model, d_v) * 0.01

    def softmax(self, x):
        e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
        return e_x / e_x.sum(axis=-1, keepdims=True)

    def forward(self, X):
        self.Q = X @ self.W_Q
        self.K = X @ self.W_K
        self.V = X @ self.W_V

        scores = self.Q @ self.K.T / np.sqrt(self.d_k)
        self.weights = self.softmax(scores)
        output = self.weights @ self.V

        return output, self.weights

# data
np.random.seed(42)

seq_len = 5
d_model = 8
d_k = 4
d_v = 4

X = np.random.randn(seq_len, d_model)

attn = SelfAttention(d_model=d_model, d_k=d_k, d_v=d_v)
output, weights = attn.forward(X)

print(f"Input shape:            {X.shape}")
print(f"Output shape:           {output.shape}")
print(f"Attention weights shape: {weights.shape}")
print(f"\nAttention weights (each row sums to 1):")
print(np.round(weights, 3))
print(f"\nRow sums: {weights.sum(axis=1)}")

Input shape:            (5, 8)
Output shape:           (5, 4)
Attention weights shape: (5, 5)

Attention weights (each row sums to 1):
[[0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]]

Row sums: [1. 1. 1. 1. 1.]


In [5]:
# simulating word embeddings with semantic structure

np.random.seed(42)

X = np.random.randn(5, 8)

# making "cat" and "mat" similar
X[1] = X[4] + np.random.randn(8) * 0.1

# making "the" appear twice
X[0] = X[3] + np.random.randn(8) * 0.1

words = ["the", "cat", "sat", "on", "mat"]

# simulating trained W_Q and W_K
attn_trained = SelfAttention(d_model=8, d_k=4, d_v=4)
attn_trained.W_Q = np.random.randn(8, 4) * 1.0
attn_trained.W_K = np.random.randn(8, 4) * 1.0

output, weights = attn_trained.forward(X)

print("Attention weights:")
print(f"{'':6}", end="")
for w in words:
    print(f"{w:8}", end="")
print()
for i, w in enumerate(words):
    print(f"{w:6}", end="")
    for j in range(5):
        print(f"{weights[i,j]:.4f}  ", end="")
    print()

Attention weights:
      the     cat     sat     on      mat     
the   0.0003  0.6173  0.0000  0.0005  0.3818  
cat   0.0308  0.4938  0.0000  0.1557  0.3197  
sat   0.1282  0.3992  0.0000  0.2377  0.2348  
on    0.0001  0.6308  0.0000  0.0003  0.3688  
mat   0.0373  0.4685  0.0000  0.1858  0.3084  
